### ISSUE TITLE
21/03/2019

### ISSUE THREAD

**Issue by ChristopherSparling** [ChristopherSparling/github-journal#1]
#21/03/2019
---
##Tasks I would like to complete:
- [x] Create and write out first entry in github issue journal
- [x] Update lol-site repository with screenshots in action + legal info
- [x] Compile list of Web Development reference materials
- [x] Investigate co-working spaces in Newmarket
- [x] Research attaching blog to website vs Medium

### I also accomplished:
- [x] Worked on Self-Authoring document

---
## Things to do Tomorrow:
- Write summary of Git best practices
- Setup blog on portfolio site
- Continue work on Self-Authoring
