### ISSUE TITLE
22/03/2019

### ISSUE THREAD

**Issue by ChristopherSparling** [ChristopherSparling/github-journal#2]
# 22/03/2019
---
## Tasks I would like to complete:

- [x] _Setup blog on portfolio site_ -> Opted to use Medium rather than setup Jekyll server
- [ ] Continue work on Self-authoring
- [x] Work through SOLID, KISS, and YAGNI reading materials
- [x] Complete functional side of timestamp API project

### I also accomplished:

- [x] Reviewed Javascript Array.prototype methods
