### ISSUE TITLE
10/04/2019

### ISSUE THREAD

**Issue by ChristopherSparling** [ChristopherSparling/github-journal#4]
# 10/04/2019
---
## Tasks I would like to complete:

- [x] Reach out to boss to finalize contract
  - Waiting to get call back
- [ ] Complete FCC Product Landing Page Project
- [x] Setup Docker on laptop, create container instance
- [x] Setup PostgreSQL on laptop
- [x] Setup MongoDB on laptop

### I also accomplished:
- Reviewed React Patterns
---
## Things to do Tomorrow:
- Setup MySQL locally
- Complete local setup for Next JS development
- Complete FCC Product Landing Page
- Begin work on following FCC project
