### ISSUE TITLE
11/04/2019

### ISSUE THREAD

**Issue by ChristopherSparling** [ChristopherSparling/github-journal#5]
# 11/04/2019
---
## Tasks I would like to complete:

- [x] Complete MySQL setup locally
- [ ] Complete local setup for Next JS development
- [ ] Work on FCC project

---
## Things to do Tomorrow:
- Research React development tools for VS Code + Chrome
- Catch up on Circuits course content
- Work an hour on FCC project
